version: '2.1'

networks:
  chainpoint-node:
    driver: bridge

services:

  postgres:
    image: postgres:9.6.5-alpine
    container_name: postgres-node-src
    restart: always
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: chainpoint
      POSTGRES_PASSWORD: chainpoint
    networks:
      - chainpoint-node

  redis:
    image: redis:4.0.2-alpine
    container_name: redis-node-src
    restart: always
    volumes:
      - ./.redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./.data/redis:/data
    networks:
      - chainpoint-node
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf

  chainpoint-node:
    image: gcr.io/chainpoint-registry/chainpoint-node:latest
    restart: on-failure
    volumes:
      - ./ip-blacklist.txt:/home/node/app/ip-blacklist.txt:ro
    build: .
    ports:
      - "9090:8080"
    networks:
      - chainpoint-node
    depends_on:
      - redis
      - postgres
    environment:
      NODE_TNT_ADDRESS: ${NODE_TNT_ADDRESS}
      CHAINPOINT_NODE_PUBLIC_URI: ${CHAINPOINT_NODE_PUBLIC_URI:-http://0.0.0.0}
      CHAINPOINT_CORE_API_BASE_URI: ${CHAINPOINT_CORE_API_BASE_URI:-http://0.0.0.0}
      CHAINPOINT_NODE_UI_PASSWORD: ${CHAINPOINT_NODE_UI_PASSWORD}
      #DEBUG: "sequelize*"
